### PR TITLE
Added SSH support

### PR DESCRIPTION
**Pull request by AlSayedGamal**
Added ssh support and default root password (for development purposes).

### CODE REVIEW

**Comment by mlaitinen** [comment]
Are you aware of [`docker exec`](https://docs.docker.com/reference/commandline/exec/)? You can basically enter a container without SSH by calling `docker exec -ti my_odoo_container /bin/bash`.

**Comment by levkar** [comment]
running sshd in a production container is a very very bad idea....

**Comment by sle-odoo** [comment]
Hello,
Thanks for your contribution, however, as @mlaitinen pointed out, ssh is not needed. I'm thus closing this pull request.

Regards

**Comment by AlSayedGamal** [comment]
I was planning to use it in development not in production.
@mlaitinen exec -it won't solve the problem I need to execute command with higher privileges including installing new system packages  libraries.

**Comment by mlaitinen** [comment]
Yes of course, but people use this image in production. That's why you shouldn't create a pull request for development-only tools.

I'm not sure why you'd want to install new packages inside a container. It's a good practice to keep the contents of Docker containers [intact](http://www.slideshare.net/jpetazzo/immutable-infrastructure-with-docker-and-containers-gluecon-2015). Usually you want to modify the Dockerfile and rebuild the image. If you are doing some serious development and Docker feels too stiff for an environment, take a look at [Vagrant](https://www.vagrantup.com/).

**Pull request closed without merging**
