### PR TITLE
[ADD] Odoo: master (11.0)

### PR DESCRIPTION
**Pull request by anassahmed**
* Odoo version master (11.0). Release 20170825.
* Added `python-html2text` as a dependency.

I think adding this would easily help users/developers to test and track the development of the upcoming release of Odoo and maybe lend a helping hand.

Hope you'll consider it.

### CODE REVIEW

**Comment by anassahmed** [comment]
@sle-odoo Please check this PR and tell me what you think?
@odony Your opinion would be appreciated too.

**Comment by anassahmed** [comment]
@odony and @sle-odoo Do you have some time to review this PR before `11.0` comes out or do I need to rework it again to work with `12.0`?!

I mean, seriously 25 days is a long time! 😄

**Comment by thomas15v** [comment]
> I mean, seriously 25 days is a long time! 
Not long enough apparently ... . Anyway I am going to use your Dockerfile in one of our projects, while waiting on Odoo to update this ... .

**Comment by anassahmed** [comment]
@thomas15v I've already given up and built a docker registry for my company with CI to build an up-to-date docker image monthly for our development projects and our customers.

**Comment by thomas15v** [comment]
Apparently python3.5 has to be used with odoo:11. I went through the trouble and did [something](https://github.com/Somko/docker/tree/master/11.0): . The current deb files on nightly can't be used since they still enforce python2.7, hence why I install odoo from source.

**Comment by anassahmed** [comment]
@thomas15v This looks like a bug that should be fixed [upstream](https://github.com/odoo/odoo/) first in the `debian` package spec.

I found this commit which should fix it: https://github.com/odoo/odoo/commit/25cae52b4f59feedd3ca13c24eb52e5e93693c2e. It's pushed 2 days ago, so the nightly builds should have picked it up by now.

I think this PR is obsolete by all means now anyway, waiting for @odony and @sle-odoo to update the repository themselves 'cause I don't think they care about our PRs anymore.

**Comment by odony** [comment]
Indeed, @d-fence has fixed the deb packages for 11.0, so the python3 dependencies should be correct now. So if you make a new Dockerfile based on `debian:stretch` you should be able to use the new 11.0 debs.
@thomas15v you tried with the [latest 11.0 debs](http://download.odoo.com/11.0/nightly/deb/), right? 

We still need to push our new 11.0 Dockerfile, @d-fence plans to verify them soon (though we're in the middle of Odoo Experience 2017, so to be honest this might have to wait until next week)

**Comment by anassahmed** [comment]
@odony I want to point to rather important reason for this PR in the first place which is to provide developers/tinkerers with an easy way to try and test the next version of Odoo (the version on `master` branch, be it `11.0` or `12.0`) through Docker containers as we already do with stable versions `8.0`, `9.0`, `10.0`. but looks like this point goes unnoticed though.

**Comment by thomas15v** [comment]
> @thomas15v you tried with the latest 11.0 debs, right?

Oh I was looking at the master debs (could it it be that the new category just recently appeared?). However I had more trouble with the new python packages and the updated wkhtmltox library on `debian:stretch`.

> I want to point to rather important reason for this PR in the first place which is to provide developers/tinkerers with an easy way to try and test the next version of Odoo (the version on master branch, be it 11.0 or 12.0) through Docker containers as we already do with stable versions 8.0, 9.0, 10.0. but looks like this point goes unnoticed though.

I think such image will have to be delivered trough something like `odoo/odoo:master`. So far I understand docker hub doesn't allow daily pushes on official images due to validation checks. But even than such images would be great.

**Comment by anassahmed** [comment]
@thomas15v No one said anything about daily pushes, but at least monthly builds will be enough.

The way Dockefile(s) written here means it's a manual change anyway; as a community we can keep an eye every month and provide the required changes for the monthly update (either for stable versions or the upcoming release). but no one pays attention to our PRs.

**Comment by jbguerraz** [comment]
@odony how is the docker odoo 11 image going ? :) so eager to try it! :)

**Comment by d-fence** [comment]
@jbguerraz I'm working on it.
Trying to solve some debian depencies first.

**Comment by jbguerraz** [comment]
@d-fence If we can be of any help, feel free !

**Comment by d-fence** [comment]
@jbguerraz Thanks a lot. The actual problem that prevent to build an official Docker image is that wkhtmltox 0.12.1.2 doesn't install in Debian Stretch. The plan is to try and test if the latest version can do the Job or repackage 0.12.1.2 for Debian ... it's in progress

**Comment by anassahmed** [comment]
@d-fence I was meaning to ask: where's the source code files for `wkhtmltox`?

I was using odoo 10 packages on CentOS 7 and I installed the `wkhtmltopdf-0.12.4` (which is in `epel-testing` right [now](https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2017-b72ec227e7)) but I couldn't get it to run with Odoo without a script that run `xvfb-run` which obviously you don't need with Debian.

**Comment by d-fence** [comment]
@anassahmed as you can see in the Dockerfile, a working version is downloaded from nightly:
https://github.com/odoo/docker/blob/f432264ad15ce8e3326f281394e1900eb9d1c903/10.0/Dockerfile#L16

**Comment by anassahmed** [comment]
@d-fence I know that, I'm talking about the source code of that `wkhtmlox` nightly deb package!

How does your `wkhtmltox` work without X11 or Xvfb but the original `wkhtmltopdf` doesn't?!

**Comment by d-fence** [comment]
Long story short, sources are on github official repo. Probably here:
https://github.com/wkhtmltopdf/wkhtmltopdf/releases/0.12.1/
And the debian dir has to be regenerated :-)

**Comment by d-fence** [comment]
@thomas15v thanks, I keep the trick :+1:

**Comment by jbguerraz** [comment]
Any news ? :)

**Comment by anassahmed** [comment]
I see that you've added Odoo 11.0 already, but you didn't consider my idea of adding `master` branch for developers who want an easy way to start contributing to the next version of the project (like do you really care about at all?).

This PR has no meaning right now anyway, so I'm closing it.

**Pull request closed without merging**
