### PR TITLE
Add ability to seed database with non-postgres user

### PR DESCRIPTION
**Pull request by thatnerdjosh**
When initializing the database without using a docker container
for postgres or without postgres user, db initialization
wasn't working

### CODE REVIEW

**Comment by kovacs-andras** [comment]
Why don't you fix the other versions too?

**Comment by NerdsvilleCEO** [comment]
@kovacs-andras I will go ahead and do that :)

**Comment by lathama** [comment]
@thatnerdjosh is this still relevant in 2024? If not please close.

**Comment by thatnerdjosh** [comment]
@lathama - looks to me like it actually is - took me a second to regather context.

I'll address this right now and update.

**Comment by thatnerdjosh** [comment]
On updating the branch it closed the PR - I'll open a new one with the changes.

**Pull request closed without merging**
