### PR TITLE
[ADD] arm64v8 images

### PR DESCRIPTION
**Pull request by derfl0**
Add specific arm64v8 images to allow native Odoo execution on arm architecture (e.g. M1)

### CODE REVIEW

**Comment by semihalf-mazur-hubert** [comment]
Hi, any updates about merging PR and providing official arm64 docker images?

**Comment by FaisalJulaidan** [comment]
Go ahead please and merge

**Review by FaisalJulaidan — COMMENTED** [review]
Please merge

**Comment by leimantas** [comment]
```
RUN WKH_VERSION=$([ "$(uname -m)" = 'aarch64' ] && echo "arm64" || echo "amd64") \
    && curl -o wkhtmltox.deb -sSL https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.buster_${WKH_VERSION}.deb \
    && apt-get install -y --no-install-recommends ./wkhtmltox.deb \
    && rm -rf /var/lib/apt/lists/* wkhtmltox.deb
```

**Comment by AaronBeaudoin** [comment]
This is increasingly a _very important_ addition for Odoo developers on macOS.

I'm currently having to write my own scripts to modify the official Dockerfile so that I can build my images natively.

**Comment by jeffryjdelarosa** [comment]
I already made the same problems , Please merge it

**Comment by derfl0** [comment]
For anyone stumbling across this issue. I am now using GitHub actions (branch: build_action) to build the images automatically: https://hub.docker.com/r/fbieringer/odoo

Feel free to use. I try to keep everything up to date.

**Comment by jeffryjdelarosa** [comment]
@derfl0 Thanks so much 😍, do you have the Debbug settings with VScode, please I cloud pay it for it.

**Comment by leimantas** [comment]
We use 0.12.6 for 2 years now. Everything works. No problems. Odoo 13,14,16. Arm based debian.

**Comment by derfl0** [comment]
@d-fence @leimantas i can also confirm that I never had problems developing on my M1 using 12.6. Lately I was working on a lot of reports and never had any trouble. Of course this does not mean that it is perfectly fine but I would also argue that as long as there is no known issue one could assume that 12.6 in fact works as intended.

I am also pretty fine, if the arm images I compile ( https://hub.docker.com/r/fbieringer/odoo ) are defined as "unofficial" but maybe you could reference them somewhere on the official page so one could stumble across them.

It would also be really great, if you could externalise ODOO_RELEASE and ODOO_SHA from the Dockerimage so that it can be used for both images without requiring changes in the actual Dockerfile every time the source code is updated.

**Comment by leimantas** [comment]
@derfl0 you can build multiarch odoo images [https://hub.docker.com/r/wbms/odoo-16.0/tags](https://hub.docker.com/r/wbms/odoo-16.0/tags)

**Comment by derfl0** [comment]
> @derfl0 you can build multiarch odoo images https://hub.docker.com/r/wbms/odoo-16.0/tags

That is true but I see no need to compile for amd64 since there is an official image for that and I would not try to mislead anyone into using an unofficial image just because they are lazy ;)

**Comment by ludovic-gasc** [comment]
Hi,

I made an attempt to support ARM for Odoo with another approach with this pull request: #466

I'm interested in your feedback.

**Comment by ludovic-gasc** [comment]
Hi all,

You can now test the ARM support of Odoo with the official container image:
https://hub.docker.com/search?q=odoo&image_filter=official

Kind regards

**Pull request closed without merging**
