### PR TITLE
[REF] Odoo 8.0-10.0: update to release 20170717

### PR DESCRIPTION
**Pull request by anassahmed**
Last version is 5 months old, there's a lot of new fixes that made its way to odoo nightly versions during this period.

I've tested building all images, and ran containers out of them, and created databases on all of them to check if they all pass correctly before creating this PR.

### CODE REVIEW

**Comment by anassahmed** [comment]
It's been 2 weeks since I submitted this PR.
Is there anything that I can do to make the process a little bit quicker?!

**Comment by thomas15v** [comment]
Meaby pinging @sle-odoo?

**Comment by anassahmed** [comment]
@thomas15v The problem is that it almost made this PR obsolete (we're better building a new image for August 1st then).

**Comment by odony** [comment]
Should be superseded by f432264ad15ce8e3326f281394e1900eb9d1c903, thanks! (pushed to official-images via docker-library/official-images#3335)
Indeed, do not hesitate to ping @sle-odoo when you'd like an update of the releases ;-)

**Comment by anassahmed** [comment]
@odony In the comment above, @thomas15v did that but @sle-odoo didn't reply for another 15 days :)

**Comment by odony** [comment]
@anassahmed I didn't say the result was guaranteed, but it helps ;-)

**Pull request closed without merging**
