### PR TITLE
[BUGFIX] Permission error on database creation

### PR DESCRIPTION
**Pull request by lcrea**
After different tests, I found that the permission problem described on #97 appears also on version 8.0 and 9.0.

This simple bugfix seems to be completely solve the problem.
Please check it out and, if you agree, merge it.
Thank you very much.

### CODE REVIEW

**Comment by lcrea** [comment]
@sylnsr 
Ok, I've fixed that as you asked. Sorry for that: this my first PR in this repo 😊 

Personally, I used to include those kind of comments in my code because, I understand what you mean and you're perfectly right, but I prefer to always have those kind of memos popping up in front of my eyes, remembering me why it's better to not change some lines of code (or to pay extra attention), instead of spending time recalling all the project history.
It's a waste of time, for me. But it's just a personal taste 😉 

Thanks a lot.

**Comment by thomas15v** [comment]
Are you sure this isn't a OSX docker related issue? For me extra-addons works fine with `o+r` (644)  on files and `o+xr` (775) for folders on linux.
Also a good way to test if the folders is accessible is by probing it with `docker exec`. Like this:

```shell
thomas15v@ubuntu:~$ docker exec -it odoo_1 ls -l /mnt/extra-addons
total 1
drwxrwxr-x  8 1000 1000 4096 May  8 14:35 timesheet_task_widget
thomas15v@ubuntu:~$ ls -l odoo/extras
total 36
drwxrwxr-x  8 thomas15v thomas15v 4096 May  8 16:35 timesheet_task_widget
thomas15v@ubuntu:~$

```

Also I don't really understand why you are using chown on `/var/lib/odoo/filestore`. These perms are already correctly set. In fact you are only making them more strict.

```shell
thomas15b@ubuntu:~$ docker exec -it odoo_1 ls -l /var/lib/odoo/filestore
total 4
drwxr-xr-x 257 odoo odoo 4096 Jun 19 12:37 db
thomas15v@ubuntu:~$ 
```

**Comment by lcrea** [comment]
@thomas15v 
It could definitely be a macOS only issue: I didn't have the occasion to test it on other platforms. Anyway, IMHO, it's always an issue that any macOS user could encounter and, for that, should be solved.

I also know that, that folder is the one used only for attachments, but it's a folder that should be there. In fact, during the init process, Odoo starts to create all the subfolders inside it.

The point is: in my case, `/var/lib/odoo/filestore` was created with `root:root` owner, not with `odoo:odoo`. Repeating the process didn't change the result: always `root:root`.

As you said, it could be a macOS Docker issue or an issue related to a previous version (the native Docker for macOS was launched only one year ago and so many things are changed since then).

I totally agree with you that my solution is just a forcing of `/var/lib/odoo/filestore` perms, but it worked for me. Moreover, this bugfix is so small that doesn't affect in any negative way the rest of the Dockerfile, nor even compromises its performances.

**Comment by d-fence** [comment]
closing too old PR.
Already fixed.

**Pull request closed without merging**
