### PR TITLE
Update env vars with defaults

### PR DESCRIPTION
**Pull request by tiangolo**
The current Image and entrypoint assume using [Docker linking](https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/) and the automatic env vars created, which is a legacy feature. 

For example, it doesn't work with [Docker networks](https://docs.docker.com/engine/userguide/networking/), so it doesn't work with Docker Compose without explicit additional env var simulating the linking env vars.

This update to the entrypoint is backwards compatible, so anyone using the legacy linking system can keep using it, but other users can use the new features.

If you want it I can update the container of version 8.0 too (but I first want to know if it's OK to you).

And if you accept the changes I will create a PR to the documentation repo explaining the behavior, defaults, env vars and example use with Docker Compose.
---
## Technical details
- By default, it expects the database to be accessible in the host `db` (which is already "required" in the documentation).
- The default Postgres port is assigned to the default Postgres port: 5432
- The env var `DB_ENV_POSTGRES_USER` (from the linking system), when not created (when not using linking) reads an env var `POSTGRES_USER`, that by default is `postgres` (although in the current versions of Odoo there's a bug when the user is not `odoo`: https://github.com/odoo/odoo/issues/10377 ).
- The env var `DB_ENV_POSTGRES_PASSWORD` (from the linking system), when not created (when not using linking) reads an env var `POSTGRES_PASSWORD`.
## Example

This would work with:

``` bash
docker run -d --name db -e POSTGRES_PASSWORD=odoo -e POSTGRES_USER=odoo postgres:9.5

docker run -d -p "8069:8069" -e POSTGRES_PASSWORD=odoo -e POSTGRES_USER=odoo --link db:db odoo:9.0
```

Or with a `docker-compose.yml` file like:

``` yml
version: '2'
services:
  server:
    image: odoo:9.0
    links:
      - db:db
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    ports:
      - '8069:8069'
  db:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
```

### CODE REVIEW

**Comment by odony** [comment]
Hi @tiangolo, thanks for the PR and the comprehensive explanation! The patch looks fine to me, you can update it to fix 8.0 as well. We'll also coordinate with #75 to update 10.0.
The update of the documentation repo will be the icing on the cake :-)

**Comment by tiangolo** [comment]
Great @odony ! I will update 8.0 too then.

I already submitted a PR to the docs with the current behavior: https://github.com/docker-library/docs/pull/720

I'll update it or create a new PR once this is merged.

---

Apart from that, I suggest adding a new modification to this PR.

The current modification reads a `POSTGRES_USER` and `POSTGRES_PASSWORD` if the linking version of those vars doesn't exists. And it sets defaults for the other two env vars (for the host and port). But the default `POSTGRES_USER` is still set to the default `POSTGRES_USER` of the Postgres image that is `postgres`. Nevertheless, even if the Postgres container was created with that user it wouldn't work in Odoo: https://github.com/odoo/odoo/issues/10377. So currently it is "required" that the Postgres user is `odoo`.

And also the two new env vars `POSTGRES_USER` and `POSTGRES_PASSWORD` would be required when not using the linking system, although the Odoo image documentation already requires (or suggests) using a specific "default" user and password in the Postgres container: `odoo`.

I suggest, adding a default of `odoo` to the variables `POSTGRES_USER` and `POSTGRES_PASSWORD` in the Odoo image (in this PR). That would match more easily the expected current behavior.

If you agree, I'll include that "new" suggested modification (those default env vars) in this and the 8.0 version. And if needed I can help with version 10.0 too.

With that, using the "new" default values, a `docker-compose.yml` could be even simpler:

```yml
version: '2'
services:
  server:
    image: odoo:9.0
    depends_on:
      - db:db
    ports:
      - '8069:8069'
  db:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
```

Tell me if you would like that new change too and I'll update this PR. Thanks!

**Comment by sle-odoo** [comment]
Hi @tiangolo,

There's indeed some issues with the `PGUSER` environment variable handling by Odoo. First, if you try to connect to the database with the `postgres` user using the `--db_user` arg of `odoo`, Odoo will not run and you'll see the message `Using the database user 'postgres' is a security risk, aborting.`.

However, if you set the `PGUSER` environment variable to `postgres`, odoo will run and correctly create the database with `postgres`, but you won't be able to connect to it due to [this method](https://github.com/odoo/odoo/blob/10.0/odoo/service/db.py#L327) that will be executed before you try to login and that simply ignore the `PGUSER` environment variable when it tries to find the database.

I made some quick fixes in revisions [1] et [2] but we are reluctant to merge them in stable versions (8-10) because it kind of changes the behavior. We are looking to improve these fixes by defining only one method that will handle the fallbacks of the pg user variables (the odoo argument, the environment variable, the user executing the odoo process) in one place.

Anyway, the conclusion is that we should not use the environment variables to make odoo connect to the database and instead use directly the --db_user, --db_password etc. I made a quick revision in af4718cdeab5642daf72381ce4c46454b711a6b1 to introduce this behaviour but it's a work in progress.

[1] https://github.com/odoo-dev/odoo/commit/f48dae4421d944513869e70b7c83d4023aeb67a3
[2] https://github.com/odoo-dev/odoo/commit/a56401e1b4b053622b3c39c5b9310bad4c2913b7

**Comment by tiangolo** [comment]
Thanks for the update @sle-odoo.

So, should I update this PR to map the env vars set in the container creation (and their defaults) to the parameters you specified, basing it on https://github.com/odoo/docker/commit/af4718cdeab5642daf72381ce4c46454b711a6b1 ?

And are you OK with setting defaults of `odoo` for the env vars?

Doing so and updating the docs (I already have a PR with that too) would greatly ease and improve the develompment and setup experience (IMHO).

Also, I see that #75 is done already, but the tag doesn't appear yet in the Hub. Can I include that one too now? Or should that be another PR?

**Comment by sle-odoo** [comment]
#75 has been merged in master but i would like to fix the environment variables issues before putting it in docker hub. I'm working on these fixes in [master-sle](https://github.com/odoo/docker/commits/master-sle) where i cherrypicked your commit in 9621c46392924e46e6ddd20c7c2da6429dbba624 along with my fixes in d4e20edc4df715f05377fe4c59f0d261ea5ec488 and eedd5718867f506436a741f5b831887934d0dc91 (your suggestion). I would like to test this a little before merging master-sle in master and sending it on docker hub.

**Comment by tiangolo** [comment]
OK, excellent @sle-odoo! 

Then just let me know if there's anything I can help with.

**Comment by sle-odoo** [comment]
Hi @tiangolo, i just submitted the changes upstream, so we can close this one. I merged your contribution in 9621c46392924e46e6ddd20c7c2da6429dbba624. I'll go back to you when i'll go through your PR on the documentation. Thanks again!

**Comment by tiangolo** [comment]
Excellent @sle-odoo ! Thanks for the update!

I will now update the PR on the documentation to reflect these new changes (it was created for the previous / now-obsolete version).

**Pull request closed without merging**
