### PR TITLE
Add latest version 20170124

### PR DESCRIPTION
**Pull request by kholioeg**
Modified the original version with the latest version 20170124 with the proper SHA1 checksum.

### CODE REVIEW

**Comment by azawawi** [comment]
Awesome PR. Please merge 👍

**Comment by azawawi** [comment]
@sle-odoo Thanks

**Comment by App-247** [comment]
How I can get sha1 checksum for a Odoo nightly package? Thanks.

**Comment by azawawi** [comment]
@App-247 Take a look at `https://nightly.odoo.com/10.0/nightly/deb/odoo_10.0.20170207_amd64.changes`. Maybe something like the following line:
```
(ODOO_VERSION=10.0.20170207; curl -s https://nightly.odoo.com/10.0/nightly/deb/odoo_${ODOO_VERSION}_amd64.changes | grep -3 'Checksums-Sha1' | grep ".deb") | cut -d " " -f 2
```

**Pull request closed without merging**
