### PR TITLE
Master config file pg credentials 2 sle

### PR DESCRIPTION
**Pull request by sle-odoo**

### CODE REVIEW

**Comment by sle-odoo** [comment]
@anassahmed 
@LeartS 

Hey,
Could you please test this PR before i merged it? So you can confirm that your issues are fixed?
It'll be very nice.

Here's what i tested so far
```
docker run -d -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo --name db postgres:9.4
docker run -p 8069:8069 --name odoo --link db:db -t odoo10local
create a db "test10" through web ui
backup "test10" and restore it as "test10-2" through web ui
> ok

docker run -p 8069:8069 --name odoo --link db:db -t odoo10local:latest -- shell
> shell open but no env because no database set
docker run -p 8069:8069 --name odoo --link db:db -t odoo10local:latest -- shell -d test10
>ok

docker run -p 8069:8069 --name odoo --link db:db -t odoo10local:latest --db-filter ^test10$
docker run -p 8069:8069 --name odoo --link db:db -t odoo10local:latest -- --db-filter ^test10$
only the database "test10" should appear
>ok

docker run -v /tmp:/mnt/extra-addons -p 8069:8069 --name odoo --link db:db --rm -t odoo10local:latest -- scaffold test_addon /mnt/extra-addons
test_addon should appear in /tmp
>ok

docker run -v /tmp:/mnt/extra-addons -p 8069:8069 --name odoo --link db:db -t odoo10local
test_addon should appear in module list after an uprade module list
>ok

docker run -d -e POSTGRES_USER=odoo2 -e POSTGRES_PASSWORD=odoo2 --name db2 postgres:9.4
docker run -p 8069:8069 --name odoo -t odoo10local:latest
docker inspect db2, find "IPAdress"
docker exec -it odoo /bin/bash
echo "db_host = IPAdress" >> /etc/odoo/odoo.conf
echo "db_user = odoo2" >> /etc/odoo/odoo.conf
echo "db_password = odoo2" >> /etc/odoo/odoo.conf
docker stop odoo
docker start -a odoo
>ok

docker rm -f odoo
docker run -p 8069:8069 -e HOST=IPAddress -e USER=odoo2 -e PASSWORD=odoo2 --name odoo -t odoo10local:latest
>ok

version: '2'
services:
  web:
    image: odoo10local:latest
    depends_on:
      - db
    ports:
      - "8069:8069"
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
>ok

version: '2'
services:
  web:
    image: odoo10local:latest
    depends_on:
      - mydb
    ports:
      - "8069:8069"
    environment:
    - HOST=mydb
    - USER=odoo2
    - PASSWORD=myodoo2

  mydb:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=odoo2
      - POSTGRES_PASSWORD=myodoo2
>ok
```

**Comment by sle-odoo** [comment]
@LeartS

**Comment by LeartS** [comment]
Hi @sle-odoo , thanks, I'll test it and let you know today

**Comment by sle-odoo** [comment]
thank you.

**Comment by LeartS** [comment]
Hi @sle-odoo, sorry for the delay.
I tested shell, config file db data, and some other stuff in my environment and it all seems to work. Thanks!

**Comment by anassahmed** [comment]
Sorry for the late response, I've tried it now after pulling the latest image from Docker Hub, and our containers are back to the normal behavior.

Thanks.

**Pull request merged**
