### PR TITLE
Add Dockerfile for 9.0 branch

### PR DESCRIPTION
**Pull request by morvans**

### CODE REVIEW

**Comment by morvans** [comment]
This is basically the same PR than https://github.com/odoo/docker/pull/34 except I chose to stick on a particular release date instead of "latest"

**Comment by sle-odoo** [comment]
Thanks!
I'll look into it tomorrow. Actually, you have to specify a release date, because of Docker policies for official images

**Comment by SamVerschueren** [comment]
Any progress on this one?

**Comment by aab-odoo** [comment]
Merged at 6e12a6494782a2aec83346cae9c77d971b0d73b3

**Pull request closed without merging**
