### PR TITLE
[FIX] Make it Available for MacOS

### PR DESCRIPTION
**Pull request by jeffryjdelarosa**
This will help to choose the right platform to make it available for Apple Chip M1

### CODE REVIEW

**Comment by jeffryjdelarosa** [comment]
@d-fence Please help us with this

**Comment by AaronBeaudoin** [comment]
#410 has already been sitting around for a while without being merged. #399 also seems to be trying to address the same problem. So now there are 3 separate open pull requests. @d-fence, we need you!

**Comment by leimantas** [comment]
[https://github.com/wkhtmltopdf/wkhtmltopdf/issues/5160](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/5160)

**Comment by ludovic-gasc** [comment]
Hi,

You can now test the ARM support of Odoo with the official container image:
https://hub.docker.com/search?q=odoo&image_filter=official

Kind regards

**Pull request closed without merging**
