### PR TITLE
ability to create docker images with specific release tags

### PR DESCRIPTION
**Pull request by steenzout**
Let me know if you are interested in the following changes:

- base images: `8.0-base`, `9.0-base` and `10.0-base`
- release specific images, e.g. `9.0.20161123`, `9.0` will point to the latest release
- ability to add more releases to be built be adding 1 line to the `releases.txt` file
- bash scripts to generate release specific images `Dockerfile`s
- bash scripts to easily start, stop and login to a Odoo release container which can be useful for debugging
- default `conf` file now defines a `logfile` parameter to make it easier to debug containers
- bash scripts to regenerate `releases.txt` file

-----
from the `HOWTO.md` file:

Repo is structured the following way:

- `${ODOO_VERSION}/`
  - `base/`
    - `Dockerfile`: file to build the `${ODOO_VERSION}-base` container image
  - `${ODOO_RELEASE}/`
    - `Dockerfile`: file to build the `${ODOO_VERSION}.${ODOO_RELEASE}` container image taking `${ODOO_VERSION}-base` as a base
  - `latest`: symlink to the latest `${ODOO_RELEASE}` release

This repo contains a few bash scripts to
help you generate docker container images.

`generate_releases.sh` will go to nightly.odoo.com and
grab the available releases and SHA1 checksum and
rebuild the `${ODOO_VERSION}/releases.txt`.

```bash
# all
$ bash generate_releases.sh

# single release
$ bash generate_releases.sh 2016-12-30
```

`generate.sh` will read the `${ODOO_VERSION}/releases.txt` file,
parse the `release:checksum` lines and
generate the `${ODOO_VERSION}/${ODOO_RELEASE}/Dockerfile`.

```bash
# all
$ bash generate.sh

# single release
$ bash generate.sh 2016-12-30
```

`build.sh` is used to build the docker container images locally.

```bash
# all
$ bash build.sh

# single release
$ bash build.sh 2016-12-30
```

There are some auxiliary bash scripts to run docker container locally.

```bash
# start an Odoo release container
$ bash start_container.sh 9.0 2016-11-23
# or
$ bash start_container.sh 9.0 20161123

# open interactive session on the Odoo container
$ bash login.sh 9.0 2016-11-23
# or
$ bash login.sh 9.0 20161123

# stop and destroy
$ bash stop_container.sh 9.0 2016-11-23
# or
$ bash stop_container.sh 9.0 20161123
```

### CODE REVIEW

**Comment by Yenthe666** [comment]
@sle-odoo check this out. Nice job @steenzout!

**Comment by sle-odoo** [comment]
Hello,
Thank you for the effort! Sadly I won't be able to have a look at this before next week. I'll go back to you then.

Regards

**Comment by steenzout** [comment]
@sle-odoo ping...

**Comment by azawawi** [comment]
@sle-odoo Any update on this one?

**Comment by sle-odoo** [comment]
Hi @steenzout, sorry for the big delay. I'm not sure this PR is really what we want for this repo. 

Indeed, having specific images per release date doesn't seem interesting (we can always look into the git history to get which Dockerfile was up at any time). Having a special script to launch the images doesn't seem interesting to me, it doesn't offer much more than the Docker interface and doesn't test the docker-compose interface.

I agree it's annoying to update the Dockerfile, but it's tow lines anyway. At this moment i think we'll go on with that.

What would be more interesting is a travis integration so that the images are build each time we push something on this repo.

Thanks for the contribution and the time you took for it.

Regards

**Comment by azawawi** [comment]
@sle-odoo Could we at least have monthly tags (e.g. `:10.2017.02`)? I totally agree on the Travis CI and maybe later add AppVeyor (for windows) integration.
@steenzout Thanks for all your awesome PR work. How about publishing it as a separate docker file in a new github/docker hub public repository?

**Comment by sle-odoo** [comment]
@azawawi Could you explain the benefits you see in monthly tags? For instance, the [postgres](https://github.com/docker-library/postgres) images doesn't do so.

**Comment by azawawi** [comment]
@sle-odoo Easier to maintain and more predictable version number? postgres point releases are released less frequently than odoo 10.x nightly.

**Comment by steenzout** [comment]
I already do that.Look for odoo image and my github handle at hub.docker.com.I'll post the link here later today.CheersOn Feb 9, 2017 3:30 AM, "Ahmad M. Zawawi" <notifications@github.com> wrote:@sle-odoo Could we at least have monthly tags (e.g. :10.2017.02)? I totally agree on the Travis CI and maybe later add AppVeyor (for windows) integration.
@steenzout Thanks for all your awesome PR work. How about publishing it as a separate docker file in a new github/docker hub public repository?

**Comment by azawawi** [comment]
@steenzout Thanks for sharing it.

**Comment by steenzout** [comment]
@azawawi [here](https://hub.docker.com/r/steenzout/odoo/tags/)

**Pull request closed without merging**
